direction: "backward"  # or "forward"
models_dir: "E:/input_models/"
output_dir: "D:/merged_model/"
metric_dir: "./metrics/"
dataset_dir: "./benchmarks/"
improve_all: "quality"  # or "bigram" or "exact" "all" or blank
samples: 1000 # (tbd) implement code to process this for number of dataset samples to evaluate 
base_model_name: "Orion-zhen/Qwen2.5-7B-Instruct-Uncensored"

models: # uncomment the models you want to merge
##### Qwen2.5 7B Models #####
- "AlekseyKorshuk/ai-detection-gutenberg-human-v2-formatted-ai-sft-qwen-7b-sft-3epochs"
- "beomi/Qwen2.5-7B-Instruct-kowiki-qa"
#- "Cran-May/T.E-8.1"
#- "DeepGlint-AI/llava-mlcd-qwen2.5-7b"
- "edgerunner-ai/EdgeRunner-Command-Nested"
- "EVA-UNIT-01/EVA-Qwen2.5-7B-v0.1"
#- "fblgit/cybertron-v4-qw7B-MGS"
- "FourOhFour/Vapor_v2_7B"
- "Goekdeniz-Guelmez/Josiefied-Qwen2.5-7B-Instruct-abliterated-v2"
- "happzy2633/qwen2.5-7b-ins-v3"
- "huihui-ai/Qwen2.5-7B-Instruct-abliterated-v2"
- "HumanLLMs/Humanish-Qwen2.5-7B-Instruct"
 "katanemo/Arch-Function-7B"
- "Orion-zhen/Meissa-Qwen2.5-7B-Instruct"
- "Orion-zhen/Qwen2.5-7B-Gutenberg-KTO"
- "Orion-zhen/Qwen2.5-7B-Instruct-Uncensored"
#- "newsbang/Homer-7B-v0.1"
- "nhyha/merge_Qwen2.5-7B-Instruct_20241023_0314"
- "Qwen/Qwen2.5-7B"
#- "Qwen/Qwen2.5-7B-Instruct"
#- "rombodawg/Rombos-LLM-V2.5-Qwen-7b"
- "scilo/qwen_ft_no_temp"
- "sethuiyer/Qwen2.5-7B-Anvita"
- "Siheng99/Qwen2.5-7B-Instruct-SEALONG"
- "thomas-yanxin/XinYuan-Qwen2.5-7B-0917"
- "newsbang/Homer-v0.5-Qwen2.5-7B"
- "fblgit/cybertron-v4-qw7B-UNAMGS"
- "win10/Verdandi-Qwen2.5-7B"
#- "win10/Norns-Qwen2.5-7B-v0.2"
#- "MadeAgents/Hammer2.0-7b"
- "AmberYifan/Qwen2.5-7B-dpo-2k"
- "nextvalueup/Qwen2.5-7B-Instruct_v3"
#- "Qwen/Qwen2.5-Coder-7B-Instruct"
#- "Qwen/Qwen2.5-Math-7B-Instruct" 
#- "Qwen/Qwen2.5-Coder-7B"
#- "Qwen/Qwen2.5-Math-7B"
#- "jbjeong91/Qwen2.5_7B_IST_StoryGen_vanilla"
- "AmberYifan/Qwen2.5-7B-dpo-2k-hhrlhf"
- "jbjeong91/Qwen2.5_7B_IST_StoryGen_test2" 
#- "OpenBuddy/openbuddy-qwen2.5llamaify-7b-v23.1-200k"
#- "WhiteRabbitNeo/WhiteRabbitNeo-2.5-Qwen-2.5-Coder-7B"
#- "BenevolenceMessiah/Qwen2.5-Coder-7B-3x-Instruct-TIES-v1.1"
#- "BenevolenceMessiah/Qwen2.5-Coder-7B-Chat-Instruct-TIES-v1.2"
- "tablegpt/TableGPT2-7B"
#- "Etherll/Qwen2.5-Coder-7B-Instruct-Ties"
- "opencompass/CompassJudger-1-7B-Instruct"
#- "nguyentd/FinancialAdvice-Qwen2.5-7B"
- "ZeroXClem/Qwen2.5-7B-HomerCreative-Mix"
#- "bunnycore/Qandora-2.5-7B"
- "allura-org/Teleut-7b"
#- "jeffmeloy/Qwen2.5-7B-minperplexity-1"
#- "jeffmeloy/Qwen2.5-7B-minperplexity-4"
- "AIDC-AI/Marco-o1"
#- "jeffmeloy/Qwen2.5-7B-olm-bbh-v1.1"
#- "THUdyh/Insight-V-Reason"
#- "THUdyh/Insight-V-Summary"
#- "qfq/Qwen2.5-7B-Instruct-20241128-215054"
#- "real-jiakai/Qwen2.5-7B-Instruct-Jiakai"
- "suayptalha/HomerCreativeAnvita-Mix-Qw7B"
- "Marsouuu/lareneg3Bv2-ECE-PRYMMAL-Martial"
- "Tsunami-th/Tsunami-1.0-7B-Instruct"
#- "prithivMLmods/Neumind-Math-7B-Instruct"
- "TIGER-Lab/ScholarCopilot-v1"
- "Henry94/Qwen2.5-7B-Character"
#- "prithivMLmods/QwQ-LCoT-7B-Instruct"
- "prithivMLmods/Novaeus-Promptist-7B-Instruct"
#- "prithivMLmods/Qwen-UMLS-7B-Instruct"
- "Spestly/Athena-1-7B"
- "winstcha/rewrite-7B-INT4"
#- "ZHIYII/Qwen2.5-7B-Reward"

dataset: 
  "longresponse_sharegpt.json":
    mode: "quality"
  "bbh_sharegpt.json":
    mode: "exact"
  "qpqa_sharegpt.json":
    mode: "exact"
  "ifeval_sharegpt.json":
    mode: "bigram"
  "math_lvl5_sharegpt.json":
    mode: "exact"
  "mmlupro_sharegpt.json":
    mode: "exact"
  "musr_sharegpt.json":
    mode: "exact"
  "truthfulqa_sharegpt.json":
    mode: "exact"
  "arc_sharegpt.json":
    mode: "exact"