direction: "forward"  # "backward" or "forward"
models_dir: "./input_models/"
output_dir: "./merged_model/"
metric_dir: "./metrics/"
dataset_dir: "./benchmarks/"
db_dir:  # either blank or a directory path to store and retreive from a sqlite db
skip_quality: false
layer_swap: false
tensor_swap: true
base_select: "bigram" # "quality" "bigram", "exact"
boundary_select:  # "quality", "bigram", "exact", or model name, or none
improve_all: "base" # "quality" "bigram", "exact", "all", "base", or blank
samples: 200 # (tbd) implement code to process this for number of dataset samples to evaluate 
base_model_name: "newsbang/Homer-v0.5-Qwen2.5-7B"
models_db: # if blank use only file system files. if true then use sqlite db to store composite model layer composition info and corresponding dataset metrics

models: # uncomment the models you want to merge
## Qwen2.5 7B Models ## 
- "AIDC-AI/Marco-o1"
- "AlekseyKorshuk/ai-detection-gutenberg-human-v2-formatted-ai-sft-qwen-7b-sft-3epochs"
- "allura-org/Teleut-7b"
- "AmberYifan/Qwen2.5-7B-dpo-2k"
- "AmberYifan/Qwen2.5-7B-dpo-2k-hhrlhf"
- "Aashraf995/Qwen-Evo-7B"
- "beomi/Qwen2.5-7B-Instruct-kowiki-qa"
- "brahmairesearch/x1-7B-v0.1"
- "bugatt/BGLLM"
- "bunnycore/Qandora-2.5-7B"
- "cooperleong00/Qwen2.5-7B-Instruct-Jailbroken"
- "DeepGlint-AI/llava-mlcd-qwen2.5-7b"
- "DrNicefellow/Qwen2.5-7B-O1-Journey-1"
- "edgerunner-ai/EdgeRunner-Command-Nested"
- "EVA-UNIT-01/EVA-Qwen2.5-7B-v0.1"
- "fblgit/cybertron-v4-qw7B-UNAMGS"
- "FourOhFour/Vapor_v2_7B"
- "FreedomIntelligence/BlenderLLM"
- "FreedomIntelligence/HuatuoGPT-o1-7B"
- "Goekdeniz-Guelmez/Josiefied-Qwen2.5-7B-Instruct-abliterated-v2"
- "happzy2633/qwen2.5-7b-ins-v3"
- "Henry94/Qwen2.5-7B-Character"
- "hotmailuser/QwenSlerp-7B"
- "huihui-ai/Qwen2.5-7B-Instruct-abliterated-v2"
- "HumanLLMs/Human-Like-Qwen2.5-7B-Instruct"
- "internlm/SWE-Fixer-Retriever-7B"
- "jbjeong91/Qwen2.5_7B_IST_StoryGen_test2"
- "katanemo/Arch-Function-7B"
- "Manual-Dataset-Creation-Project/Take-7B"
- "Manual-Dataset-Creation-Project/Matsu-7B"
- "Marsouuu/lareneg3Bv2-ECE-PRYMMAL-Martial"
- "mlfoundations-dev/hp_ablations_qwen_epoch2"
- "neopolita/jessi-v0.1-qwen2.5-7b-instruct"
- "newsbang/Homer-v0.5-Qwen2.5-7B"
- "nextvalueup/Qwen2.5-7B-Instruct_v3"
- "nhyha/merge_Qwen2.5-7B-Instruct_20241023_0314"
- "opencompass/CompassJudger-1-7B-Instruct"
- "Orion-zhen/Meissa-Qwen2.5-7B-Instruct"
- "Orion-zhen/Qwen2.5-7B-Gutenberg-KTO"
- "Orion-zhen/Qwen2.5-7B-Instruct-Uncensored"
- "qingy2024/UwU-7B-Instruct"
- "Qwen/Qwen2.5-7B"
- "Qwen/Qwen2.5-7B-Instruct"
- "qfq/Qwen2.5-7B-Instruct-20241128-215054"
- "rombodawg/Rombos-LLM-V2.5-Qwen-7b"
- "prithivMLmods/Deepthink-Reasoning-7B"
- "prithivMLmods/Novaeus-Promptist-7B-Instruct"
- "prithivMLmods/QwQ-MathOct-7B"
- "scilo/qwen_ft_no_temp"
- "sethuiyer/Qwen2.5-7B-Anvita"
- "Siheng99/Qwen2.5-7B-Instruct-SEALONG"
- "SJTULean/LeanFormalizer_CoT"
- "SJTULean/LeanFormalizer_PPO"
- "SJTULean/LeanFormalizer_SFT"
- "sometimesanotion/KytheraMix-7B-v0.2"
- "Spestly/Athena-1-7B"
- "suayptalha/HomerCreativeAnvita-Mix-Qw7B"
- "tablegpt/TableGPT2-7B"
- "TIGER-Lab/ScholarCopilot-v1"
- "thomas-yanxin/XinYuan-Qwen2.5-7B-0917"
- "Tsunami-th/Tsunami-1.0-7B-Instruct"
- "tugstugi/Qwen2.5-7B-Instruct-QwQ-v0.1"
- "win10/Verdandi-Qwen2.5-7B"
- "winstcha/rewrite-7B-INT4"
- "yellowtown/7B-v0.2"
- "ZeroXClem/Qwen2.5-7B-HomerAnvita-NerdMix"
- "ZeroXClem/Qwen2.5-7B-HomerCreative-Mix"
- "Bui1dMySea/LongRAG-Qwen2.5-7B-Instruct"
- "Ba2han/Qwen-2.5-7B-Woonderer-0.1"
- "bespokelabs/Bespoke-Stratos-7B"
- "mlfoundations-dev/Bespoke-Stratos-17k-v3"

#- "bytedance-research/Valley-Eagle-7B"
#- "Cran-May/T.E-8.1"
#- "MadeAgents/Hammer2.0-7b"
#- "Qwen/Qwen2.5-Coder-7B-Instruct"
#- "Qwen/Qwen2.5-Math-7B-Instruct" 
#- "Qwen/Qwen2.5-Coder-7B"
#- "Qwen/Qwen2.5-Math-7B"
#- "OpenBuddy/openbuddy-qwen2.5llamaify-7b-v23.1-200k"
#- "WhiteRabbitNeo/WhiteRabbitNeo-2.5-Qwen-2.5-Coder-7B"
#- "BenevolenceMessiah/Qwen2.5-Coder-7B-3x-Instruct-TIES-v1.1"
#- "BenevolenceMessiah/Qwen2.5-Coder-7B-Chat-Instruct-TIES-v1.2"
#- "Etherll/Qwen2.5-Coder-7B-Instruct-Ties"
#- "THUdyh/Insight-V-Reason"
#- "THUdyh/Insight-V-Summary"
#- "nguyentd/FinancialAdvice-Qwen2.5-7B"
#- "jbjeong91/Qwen2.5_7B_IST_StoryGen_vanilla"
#- "Qwen/Qwen2.5-7B-Instruct"
#- "real-jiakai/Qwen2.5-7B-Instruct-Jiakai"
#- "prithivMLmods/Neumind-Math-7B-Instruct"
#- "prithivMLmods/QwQ-LCoT-7B-Instruct"
#- "prithivMLmods/Qwen-UMLS-7B-Instruct"
#- "ZHIYII/Qwen2.5-7B-Reward"

dataset:
  "ifeval_sharegpt.json":
    mode: "bigram" 
  "bbh_sharegpt.json":
    mode: "exact"
  "qpqa_sharegpt.json":
    mode: "exact"
  "math_lvl5_sharegpt.json":
    mode: "exact"
  "mmlupro_sharegpt.json":
    mode: "exact"
  "musr_sharegpt.json":
    mode: "exact"
  "truthfulqa_sharegpt.json":
    mode: "exact"
  "arc_sharegpt.json":
    mode: "exact"
  "longresponse_sharegpt.json":
    mode: "quality"